apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    app: tomcat
spec:
  containers:
  - name: tomcat-container
    image: nithishnithi/tomcat4
    ports:
    - containerPort: 8080
